# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.AnalyticsInterval do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :date_from,
    :date_to,
    :metrics,
    :additional_fields,
    :custom_fields
  ]

  @type t :: %__MODULE__{
    :date_from => String.t | nil,
    :date_to => String.t | nil,
    :metrics => API2CartOpenAPI.Model.AnalyticsMetric.t | nil,
    :additional_fields => map() | nil,
    :custom_fields => map() | nil
  }

  alias API2CartOpenAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:metrics, :struct, API2CartOpenAPI.Model.AnalyticsMetric)
  end
end

