# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.AnalyticsProduct do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :product_id,
    :variant_id,
    :sku,
    :name,
    :category_ids,
    :metrics,
    :additional_fields,
    :custom_fields
  ]

  @type t :: %__MODULE__{
    :product_id => String.t | nil,
    :variant_id => String.t | nil,
    :sku => String.t | nil,
    :name => String.t | nil,
    :category_ids => [String.t] | nil,
    :metrics => API2CartOpenAPI.Model.AnalyticsProductMetric.t | nil,
    :additional_fields => map() | nil,
    :custom_fields => map() | nil
  }

  alias API2CartOpenAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:metrics, :struct, API2CartOpenAPI.Model.AnalyticsProductMetric)
  end
end

