# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.AnalyticsCustomerMetric do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :orders_count,
    :total_spend,
    :avg_order_value,
    :currency_id,
    :additional_fields,
    :custom_fields
  ]

  @type t :: %__MODULE__{
    :orders_count => integer() | nil,
    :total_spend => float() | nil,
    :avg_order_value => float() | nil,
    :currency_id => String.t | nil,
    :additional_fields => map() | nil,
    :custom_fields => map() | nil
  }

  def decode(value) do
    value
  end
end

