# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.AnalyticsProductMetric do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :items_sold,
    :orders_count,
    :gross_sales,
    :net_sales,
    :discounts,
    :refunds,
    :currency_id,
    :additional_fields,
    :custom_fields
  ]

  @type t :: %__MODULE__{
    :items_sold => integer() | nil,
    :orders_count => integer() | nil,
    :gross_sales => float() | nil,
    :net_sales => float() | nil,
    :discounts => float() | nil,
    :refunds => float() | nil,
    :currency_id => String.t | nil,
    :additional_fields => map() | nil,
    :custom_fields => map() | nil
  }

  def decode(value) do
    value
  end
end

