# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.BaseCustomer do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :email,
    :first_name,
    :last_name,
    :phone,
    :additional_fields,
    :custom_fields
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :email => String.t | nil,
    :first_name => String.t | nil,
    :last_name => String.t | nil,
    :phone => String.t | nil,
    :additional_fields => map() | nil,
    :custom_fields => map() | nil
  }

  def decode(value) do
    value
  end
end

