# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.BasketItem do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :parent_id,
    :product_id,
    :variant_id,
    :sku,
    :name,
    :price,
    :tax,
    :quantity,
    :weight_unit,
    :weight,
    :options,
    :additional_fields,
    :custom_fields
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :parent_id => String.t | nil,
    :product_id => String.t | nil,
    :variant_id => String.t | nil,
    :sku => String.t | nil,
    :name => String.t | nil,
    :price => float() | nil,
    :tax => float() | nil,
    :quantity => float() | nil,
    :weight_unit => String.t | nil,
    :weight => float() | nil,
    :options => [API2CartOpenAPI.Model.BasketItemOption.t] | nil,
    :additional_fields => map() | nil,
    :custom_fields => map() | nil
  }

  alias API2CartOpenAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:options, :list, API2CartOpenAPI.Model.BasketItemOption)
  end
end

