# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.BasketItemOption do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :value_id,
    :name,
    :value,
    :used_in_combination,
    :additional_fields,
    :custom_fields
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :value_id => String.t | nil,
    :name => String.t | nil,
    :value => String.t | nil,
    :used_in_combination => boolean() | nil,
    :additional_fields => map() | nil,
    :custom_fields => map() | nil
  }

  def decode(value) do
    value
  end
end

