# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.CartConfigUpdate do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :db_tables_prefix,
    :custom_fields,
    :store_id,
    :user_agent
  ]

  @type t :: %__MODULE__{
    :db_tables_prefix => String.t | nil,
    :custom_fields => map() | nil,
    :store_id => String.t | nil,
    :user_agent => String.t | nil
  }

  def decode(value) do
    value
  end
end

