# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.CartCouponAdd do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :code,
    :action_type,
    :action_apply_to,
    :action_scope,
    :action_amount,
    :codes,
    :name,
    :date_start,
    :date_end,
    :usage_limit,
    :usage_limit_per_customer,
    :action_condition_entity,
    :action_condition_key,
    :action_condition_operator,
    :action_condition_value,
    :include_tax,
    :store_id
  ]

  @type t :: %__MODULE__{
    :code => String.t,
    :action_type => String.t,
    :action_apply_to => String.t,
    :action_scope => String.t,
    :action_amount => float(),
    :codes => [String.t] | nil,
    :name => String.t | nil,
    :date_start => String.t | nil,
    :date_end => String.t | nil,
    :usage_limit => integer() | nil,
    :usage_limit_per_customer => integer() | nil,
    :action_condition_entity => String.t | nil,
    :action_condition_key => String.t | nil,
    :action_condition_operator => String.t | nil,
    :action_condition_value => String.t | nil,
    :include_tax => boolean() | nil,
    :store_id => String.t | nil
  }

  def decode(value) do
    value
  end
end

