# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.CartPickupLocation do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :name,
    :avail,
    :address,
    :pickup_instructions,
    :expected_ready_time,
    :additional_fields,
    :custom_fields
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :name => String.t | nil,
    :avail => boolean() | nil,
    :address => API2CartOpenAPI.Model.CustomerAddress.t | nil,
    :pickup_instructions => String.t | nil,
    :expected_ready_time => String.t | nil,
    :additional_fields => map() | nil,
    :custom_fields => map() | nil
  }

  alias API2CartOpenAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:address, :struct, API2CartOpenAPI.Model.CustomerAddress)
  end
end

