# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.CartStoreInfo do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :store_id,
    :name,
    :language,
    :store_languages,
    :currency,
    :store_currencies,
    :timezone,
    :country,
    :root_category_id,
    :multi_store_url,
    :active,
    :weight_unit,
    :dimension_unit,
    :prices_include_tax,
    :carrier_info,
    :store_owner_info,
    :default_warehouse_id,
    :channels,
    :pickup_locations,
    :additional_fields,
    :custom_fields
  ]

  @type t :: %__MODULE__{
    :store_id => String.t | nil,
    :name => String.t | nil,
    :language => String.t | nil,
    :store_languages => [API2CartOpenAPI.Model.Language.t] | nil,
    :currency => API2CartOpenAPI.Model.Currency.t | nil,
    :store_currencies => [API2CartOpenAPI.Model.Currency.t] | nil,
    :timezone => String.t | nil,
    :country => String.t | nil,
    :root_category_id => String.t | nil,
    :multi_store_url => String.t | nil,
    :active => boolean() | nil,
    :weight_unit => String.t | nil,
    :dimension_unit => String.t | nil,
    :prices_include_tax => boolean() | nil,
    :carrier_info => [API2CartOpenAPI.Model.Carrier.t] | nil,
    :store_owner_info => API2CartOpenAPI.Model.Info.t | nil,
    :default_warehouse_id => String.t | nil,
    :channels => [API2CartOpenAPI.Model.CartChannel.t] | nil,
    :pickup_locations => [API2CartOpenAPI.Model.CartPickupLocation.t] | nil,
    :additional_fields => map() | nil,
    :custom_fields => map() | nil
  }

  alias API2CartOpenAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:store_languages, :list, API2CartOpenAPI.Model.Language)
     |> Deserializer.deserialize(:currency, :struct, API2CartOpenAPI.Model.Currency)
     |> Deserializer.deserialize(:store_currencies, :list, API2CartOpenAPI.Model.Currency)
     |> Deserializer.deserialize(:carrier_info, :list, API2CartOpenAPI.Model.Carrier)
     |> Deserializer.deserialize(:store_owner_info, :struct, API2CartOpenAPI.Model.Info)
     |> Deserializer.deserialize(:channels, :list, API2CartOpenAPI.Model.CartChannel)
     |> Deserializer.deserialize(:pickup_locations, :list, API2CartOpenAPI.Model.CartPickupLocation)
  end
end

