# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.CartShippingMethodRate do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :min_weight,
    :max_weight,
    :min_order_amount,
    :max_order_amount,
    :min_items_count,
    :max_items_count,
    :price,
    :additional_fields,
    :custom_fields
  ]

  @type t :: %__MODULE__{
    :min_weight => String.t | nil,
    :max_weight => String.t | nil,
    :min_order_amount => String.t | nil,
    :max_order_amount => String.t | nil,
    :min_items_count => String.t | nil,
    :max_items_count => String.t | nil,
    :price => String.t | nil,
    :additional_fields => map() | nil,
    :custom_fields => map() | nil
  }

  def decode(value) do
    value
  end
end

