# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.CartShippingMethod do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :name,
    :handling_fee,
    :handling_enabled,
    :handling_type,
    :default_price,
    :default_price_type,
    :type,
    :enabled,
    :min_order_amount,
    :rates,
    :additional_fields,
    :custom_fields
  ]

  @type t :: %__MODULE__{
    :name => String.t | nil,
    :handling_fee => String.t | nil,
    :handling_enabled => String.t | nil,
    :handling_type => String.t | nil,
    :default_price => String.t | nil,
    :default_price_type => String.t | nil,
    :type => String.t | nil,
    :enabled => String.t | nil,
    :min_order_amount => String.t | nil,
    :rates => [API2CartOpenAPI.Model.CartShippingMethodRate.t] | nil,
    :additional_fields => map() | nil,
    :custom_fields => map() | nil
  }

  alias API2CartOpenAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:rates, :list, API2CartOpenAPI.Model.CartShippingMethodRate)
  end
end

