# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.Cart do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :name,
    :url,
    :version,
    :bridge_version,
    :default_rounding_precision,
    :db_prefix,
    :stores_info,
    :warehouses,
    :shipping_zones,
    :additional_fields,
    :custom_fields
  ]

  @type t :: %__MODULE__{
    :name => String.t | nil,
    :url => String.t | nil,
    :version => String.t | nil,
    :bridge_version => String.t | nil,
    :default_rounding_precision => integer() | nil,
    :db_prefix => String.t | nil,
    :stores_info => [API2CartOpenAPI.Model.CartStoreInfo.t] | nil,
    :warehouses => [API2CartOpenAPI.Model.CartWarehouse.t] | nil,
    :shipping_zones => [API2CartOpenAPI.Model.CartShippingZone.t] | nil,
    :additional_fields => map() | nil,
    :custom_fields => map() | nil
  }

  alias API2CartOpenAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:stores_info, :list, API2CartOpenAPI.Model.CartStoreInfo)
     |> Deserializer.deserialize(:warehouses, :list, API2CartOpenAPI.Model.CartWarehouse)
     |> Deserializer.deserialize(:shipping_zones, :list, API2CartOpenAPI.Model.CartShippingZone)
  end
end

