# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.CategoryAddBatchPayloadInner do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :name,
    :avail,
    :description,
    :meta_title,
    :meta_description,
    :meta_keywords,
    :parent_id,
    :sort_order,
    :seo_url,
    :store_id,
    :images,
    :stores_ids
  ]

  @type t :: %__MODULE__{
    :name => String.t,
    :avail => boolean() | nil,
    :description => String.t | nil,
    :meta_title => String.t | nil,
    :meta_description => String.t | nil,
    :meta_keywords => [String.t] | nil,
    :parent_id => String.t | nil,
    :sort_order => integer() | nil,
    :seo_url => String.t | nil,
    :store_id => String.t | nil,
    :images => [API2CartOpenAPI.Model.CategoryAddBatchPayloadInnerImagesInner.t] | nil,
    :stores_ids => [String.t] | nil
  }

  alias API2CartOpenAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:images, :list, API2CartOpenAPI.Model.CategoryAddBatchPayloadInnerImagesInner)
  end
end

