# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.CategoryAddBatch do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :payload
  ]

  @type t :: %__MODULE__{
    :payload => [API2CartOpenAPI.Model.CategoryAddBatchPayloadInner.t]
  }

  alias API2CartOpenAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:payload, :list, API2CartOpenAPI.Model.CategoryAddBatchPayloadInner)
  end
end

