# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.Category do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :parent_id,
    :created_at,
    :modified_at,
    :name,
    :short_description,
    :description,
    :stores_ids,
    :keywords,
    :meta_description,
    :meta_title,
    :avail,
    :path,
    :seo_url,
    :sort_order,
    :images,
    :additional_fields,
    :custom_fields
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :parent_id => String.t | nil,
    :created_at => API2CartOpenAPI.Model.A2CDateTime.t | nil,
    :modified_at => API2CartOpenAPI.Model.A2CDateTime.t | nil,
    :name => String.t | nil,
    :short_description => String.t | nil,
    :description => String.t | nil,
    :stores_ids => [String.t] | nil,
    :keywords => String.t | nil,
    :meta_description => String.t | nil,
    :meta_title => String.t | nil,
    :avail => boolean() | nil,
    :path => String.t | nil,
    :seo_url => String.t | nil,
    :sort_order => integer() | nil,
    :images => [API2CartOpenAPI.Model.Image.t] | nil,
    :additional_fields => map() | nil,
    :custom_fields => map() | nil
  }

  alias API2CartOpenAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:created_at, :struct, API2CartOpenAPI.Model.A2CDateTime)
     |> Deserializer.deserialize(:modified_at, :struct, API2CartOpenAPI.Model.A2CDateTime)
     |> Deserializer.deserialize(:images, :list, API2CartOpenAPI.Model.Image)
  end
end

