# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.CategoryAssign200Response do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :return_code,
    :return_message,
    :result
  ]

  @type t :: %__MODULE__{
    :return_code => integer() | nil,
    :return_message => String.t | nil,
    :result => map() | nil
  }

  def decode(value) do
    value
  end
end

