# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.CategoryAddBatchPayloadInnerImagesInner do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :url,
    :image_name,
    :type,
    :label
  ]

  @type t :: %__MODULE__{
    :url => String.t,
    :image_name => String.t | nil,
    :type => String.t | nil,
    :label => String.t | nil
  }

  def decode(value) do
    value
  end
end

