# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.Child do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :parent_id,
    :sku,
    :upc,
    :ean,
    :mpn,
    :gtin,
    :isbn,
    :url,
    :seo_url,
    :sort_order,
    :created_time,
    :modified_time,
    :name,
    :short_description,
    :full_description,
    :images,
    :combination,
    :default_price,
    :cost_price,
    :list_price,
    :wholesale_price,
    :advanced_price,
    :tax_class_id,
    :avail_for_sale,
    :allow_backorders,
    :in_stock,
    :on_sale,
    :manage_stock,
    :inventory_level,
    :inventory,
    :min_quantity,
    :low_stock_threshold,
    :default_qty_in_pack,
    :is_qty_in_pack_fixed,
    :weight_unit,
    :weight,
    :dimensions_unit,
    :width,
    :height,
    :length,
    :meta_title,
    :meta_description,
    :meta_keywords,
    :discounts,
    :is_virtual,
    :additional_fields,
    :custom_fields
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :parent_id => String.t | nil,
    :sku => String.t | nil,
    :upc => String.t | nil,
    :ean => String.t | nil,
    :mpn => String.t | nil,
    :gtin => String.t | nil,
    :isbn => String.t | nil,
    :url => String.t | nil,
    :seo_url => String.t | nil,
    :sort_order => integer() | nil,
    :created_time => API2CartOpenAPI.Model.A2CDateTime.t | nil,
    :modified_time => API2CartOpenAPI.Model.A2CDateTime.t | nil,
    :name => String.t | nil,
    :short_description => String.t | nil,
    :full_description => String.t | nil,
    :images => [API2CartOpenAPI.Model.Image.t] | nil,
    :combination => [API2CartOpenAPI.Model.ProductChildItemCombination.t] | nil,
    :default_price => float() | nil,
    :cost_price => float() | nil,
    :list_price => float() | nil,
    :wholesale_price => float() | nil,
    :advanced_price => [API2CartOpenAPI.Model.ProductAdvancedPrice.t] | nil,
    :tax_class_id => String.t | nil,
    :avail_for_sale => boolean() | nil,
    :allow_backorders => boolean() | nil,
    :in_stock => boolean() | nil,
    :on_sale => boolean() | nil,
    :manage_stock => boolean() | nil,
    :inventory_level => float() | nil,
    :inventory => [API2CartOpenAPI.Model.ProductInventory.t] | nil,
    :min_quantity => float() | nil,
    :low_stock_threshold => float() | nil,
    :default_qty_in_pack => float() | nil,
    :is_qty_in_pack_fixed => boolean() | nil,
    :weight_unit => String.t | nil,
    :weight => float() | nil,
    :dimensions_unit => String.t | nil,
    :width => float() | nil,
    :height => float() | nil,
    :length => float() | nil,
    :meta_title => String.t | nil,
    :meta_description => String.t | nil,
    :meta_keywords => String.t | nil,
    :discounts => [API2CartOpenAPI.Model.Discount.t] | nil,
    :is_virtual => boolean() | nil,
    :additional_fields => map() | nil,
    :custom_fields => map() | nil
  }

  alias API2CartOpenAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:created_time, :struct, API2CartOpenAPI.Model.A2CDateTime)
     |> Deserializer.deserialize(:modified_time, :struct, API2CartOpenAPI.Model.A2CDateTime)
     |> Deserializer.deserialize(:images, :list, API2CartOpenAPI.Model.Image)
     |> Deserializer.deserialize(:combination, :list, API2CartOpenAPI.Model.ProductChildItemCombination)
     |> Deserializer.deserialize(:advanced_price, :list, API2CartOpenAPI.Model.ProductAdvancedPrice)
     |> Deserializer.deserialize(:inventory, :list, API2CartOpenAPI.Model.ProductInventory)
     |> Deserializer.deserialize(:discounts, :list, API2CartOpenAPI.Model.Discount)
  end
end

