# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.CouponAction do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :scope,
    :apply_to,
    :amount,
    :currency_code,
    :include_tax,
    :type,
    :discounted_quantity,
    :discount_quantity_step,
    :logic_operator,
    :conditions,
    :additional_fields,
    :custom_fields
  ]

  @type t :: %__MODULE__{
    :scope => String.t | nil,
    :apply_to => String.t | nil,
    :amount => float() | nil,
    :currency_code => String.t | nil,
    :include_tax => boolean() | nil,
    :type => String.t | nil,
    :discounted_quantity => float() | nil,
    :discount_quantity_step => integer() | nil,
    :logic_operator => String.t | nil,
    :conditions => [API2CartOpenAPI.Model.CouponCondition.t] | nil,
    :additional_fields => map() | nil,
    :custom_fields => map() | nil
  }

  alias API2CartOpenAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:conditions, :list, API2CartOpenAPI.Model.CouponCondition)
  end
end

