# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.Coupon do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :code,
    :codes,
    :name,
    :description,
    :actions,
    :date_start,
    :date_end,
    :avail,
    :priority,
    :used_times,
    :usage_limit,
    :usage_limit_per_customer,
    :logic_operator,
    :conditions,
    :usage_history,
    :additional_fields,
    :custom_fields
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :code => String.t | nil,
    :codes => [API2CartOpenAPI.Model.CouponCode.t] | nil,
    :name => String.t | nil,
    :description => String.t | nil,
    :actions => [API2CartOpenAPI.Model.CouponAction.t] | nil,
    :date_start => API2CartOpenAPI.Model.A2CDateTime.t | nil,
    :date_end => API2CartOpenAPI.Model.A2CDateTime.t | nil,
    :avail => boolean() | nil,
    :priority => integer() | nil,
    :used_times => integer() | nil,
    :usage_limit => integer() | nil,
    :usage_limit_per_customer => integer() | nil,
    :logic_operator => String.t | nil,
    :conditions => [API2CartOpenAPI.Model.CouponCondition.t] | nil,
    :usage_history => [API2CartOpenAPI.Model.CouponHistory.t] | nil,
    :additional_fields => map() | nil,
    :custom_fields => map() | nil
  }

  alias API2CartOpenAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:codes, :list, API2CartOpenAPI.Model.CouponCode)
     |> Deserializer.deserialize(:actions, :list, API2CartOpenAPI.Model.CouponAction)
     |> Deserializer.deserialize(:date_start, :struct, API2CartOpenAPI.Model.A2CDateTime)
     |> Deserializer.deserialize(:date_end, :struct, API2CartOpenAPI.Model.A2CDateTime)
     |> Deserializer.deserialize(:conditions, :list, API2CartOpenAPI.Model.CouponCondition)
     |> Deserializer.deserialize(:usage_history, :list, API2CartOpenAPI.Model.CouponHistory)
  end
end

