# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.CouponCondition do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :entity,
    :match_items,
    :key,
    :operator,
    :value,
    :logic_operator,
    :"sub-conditions",
    :additional_fields,
    :custom_fields
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :entity => String.t | nil,
    :match_items => String.t | nil,
    :key => String.t | nil,
    :operator => String.t | nil,
    :value => String.t | nil,
    :logic_operator => String.t | nil,
    :"sub-conditions" => [API2CartOpenAPI.Model.CouponCondition.t] | nil,
    :additional_fields => map() | nil,
    :custom_fields => map() | nil
  }

  alias API2CartOpenAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:"sub-conditions", :list, API2CartOpenAPI.Model.CouponCondition)
  end
end

