# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.Customer do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :email,
    :first_name,
    :last_name,
    :phone,
    :created_time,
    :modified_time,
    :group,
    :login,
    :last_login,
    :birth_day,
    :status,
    :news_letter_subscription,
    :consents,
    :gender,
    :stores_ids,
    :website,
    :fax,
    :company,
    :ip_address,
    :address_book,
    :lang_id,
    :orders_count,
    :last_order_id,
    :additional_fields,
    :custom_fields
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :email => String.t | nil,
    :first_name => String.t | nil,
    :last_name => String.t | nil,
    :phone => String.t | nil,
    :created_time => API2CartOpenAPI.Model.A2CDateTime.t | nil,
    :modified_time => API2CartOpenAPI.Model.A2CDateTime.t | nil,
    :group => [API2CartOpenAPI.Model.CustomerGroup.t] | nil,
    :login => String.t | nil,
    :last_login => API2CartOpenAPI.Model.A2CDateTime.t | nil,
    :birth_day => API2CartOpenAPI.Model.A2CDateTime.t | nil,
    :status => String.t | nil,
    :news_letter_subscription => boolean() | nil,
    :consents => [API2CartOpenAPI.Model.CustomerConsent.t] | nil,
    :gender => String.t | nil,
    :stores_ids => [String.t] | nil,
    :website => String.t | nil,
    :fax => String.t | nil,
    :company => String.t | nil,
    :ip_address => String.t | nil,
    :address_book => [API2CartOpenAPI.Model.CustomerAddress.t] | nil,
    :lang_id => String.t | nil,
    :orders_count => integer() | nil,
    :last_order_id => String.t | nil,
    :additional_fields => map() | nil,
    :custom_fields => map() | nil
  }

  alias API2CartOpenAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:created_time, :struct, API2CartOpenAPI.Model.A2CDateTime)
     |> Deserializer.deserialize(:modified_time, :struct, API2CartOpenAPI.Model.A2CDateTime)
     |> Deserializer.deserialize(:group, :list, API2CartOpenAPI.Model.CustomerGroup)
     |> Deserializer.deserialize(:last_login, :struct, API2CartOpenAPI.Model.A2CDateTime)
     |> Deserializer.deserialize(:birth_day, :struct, API2CartOpenAPI.Model.A2CDateTime)
     |> Deserializer.deserialize(:consents, :list, API2CartOpenAPI.Model.CustomerConsent)
     |> Deserializer.deserialize(:address_book, :list, API2CartOpenAPI.Model.CustomerAddress)
  end
end

