# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.CustomerAttribute do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :attribute_id,
    :code,
    :name,
    :type,
    :values,
    :additional_fields,
    :custom_fields
  ]

  @type t :: %__MODULE__{
    :attribute_id => String.t | nil,
    :code => String.t | nil,
    :name => String.t | nil,
    :type => String.t | nil,
    :values => [API2CartOpenAPI.Model.CustomerAttributeValue.t] | nil,
    :additional_fields => map() | nil,
    :custom_fields => map() | nil
  }

  alias API2CartOpenAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:values, :list, API2CartOpenAPI.Model.CustomerAttributeValue)
  end
end

