# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.CustomerAddressAdd do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :customer_id,
    :store_id,
    :first_name,
    :last_name,
    :company,
    :address1,
    :address2,
    :city,
    :country,
    :state,
    :postcode,
    :identification_number,
    :types,
    :default,
    :phone,
    :phone_mobile,
    :fax,
    :website,
    :gender,
    :tax_id,
    :alias,
    :idempotency_key
  ]

  @type t :: %__MODULE__{
    :customer_id => String.t,
    :store_id => String.t | nil,
    :first_name => String.t | nil,
    :last_name => String.t | nil,
    :company => String.t | nil,
    :address1 => String.t,
    :address2 => String.t | nil,
    :city => String.t,
    :country => String.t,
    :state => String.t | nil,
    :postcode => String.t,
    :identification_number => String.t | nil,
    :types => [String.t] | nil,
    :default => boolean() | nil,
    :phone => String.t | nil,
    :phone_mobile => String.t | nil,
    :fax => String.t | nil,
    :website => String.t | nil,
    :gender => String.t | nil,
    :tax_id => String.t | nil,
    :alias => String.t | nil,
    :idempotency_key => String.t | nil
  }

  def decode(value) do
    value
  end
end

