# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.CustomerWishList do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :name,
    :description,
    :is_public,
    :created_at,
    :modified_at,
    :products,
    :additional_fields,
    :custom_fields
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :name => String.t | nil,
    :description => String.t | nil,
    :is_public => String.t | nil,
    :created_at => API2CartOpenAPI.Model.A2CDateTime.t | nil,
    :modified_at => API2CartOpenAPI.Model.A2CDateTime.t | nil,
    :products => [API2CartOpenAPI.Model.CustomerWishListItem.t] | nil,
    :additional_fields => map() | nil,
    :custom_fields => map() | nil
  }

  alias API2CartOpenAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:created_at, :struct, API2CartOpenAPI.Model.A2CDateTime)
     |> Deserializer.deserialize(:modified_at, :struct, API2CartOpenAPI.Model.A2CDateTime)
     |> Deserializer.deserialize(:products, :list, API2CartOpenAPI.Model.CustomerWishListItem)
  end
end

