# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.CustomerUpdate do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :group_id,
    :group_ids,
    :group,
    :email,
    :phone,
    :first_name,
    :last_name,
    :birth_day,
    :news_letter_subscription,
    :consents,
    :tags,
    :gender,
    :store_id,
    :note,
    :status,
    :address
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :group_id => String.t | nil,
    :group_ids => String.t | nil,
    :group => String.t | nil,
    :email => String.t | nil,
    :phone => String.t | nil,
    :first_name => String.t | nil,
    :last_name => String.t | nil,
    :birth_day => String.t | nil,
    :news_letter_subscription => boolean() | nil,
    :consents => [API2CartOpenAPI.Model.CustomerAddConsentsInner.t] | nil,
    :tags => String.t | nil,
    :gender => String.t | nil,
    :store_id => String.t | nil,
    :note => String.t | nil,
    :status => String.t | nil,
    :address => [API2CartOpenAPI.Model.CustomerUpdateAddressInner.t] | nil
  }

  alias API2CartOpenAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:consents, :list, API2CartOpenAPI.Model.CustomerAddConsentsInner)
     |> Deserializer.deserialize(:address, :list, API2CartOpenAPI.Model.CustomerUpdateAddressInner)
  end
end

