# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.CustomerAddConsentsInner do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :type,
    :status,
    :opt_in_level
  ]

  @type t :: %__MODULE__{
    :type => String.t,
    :status => String.t,
    :opt_in_level => String.t
  }

  def decode(value) do
    value
  end
end

