# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.CustomerWishListItem do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :product_id,
    :child_id,
    :created_time,
    :additional_fields,
    :custom_fields
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :product_id => String.t | nil,
    :child_id => String.t | nil,
    :created_time => API2CartOpenAPI.Model.A2CDateTime.t | nil,
    :additional_fields => map() | nil,
    :custom_fields => map() | nil
  }

  alias API2CartOpenAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:created_time, :struct, API2CartOpenAPI.Model.A2CDateTime)
  end
end

