# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.CustomerConsent do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :type,
    :status,
    :source,
    :opt_in_level,
    :modified_time,
    :additional_fields,
    :custom_fields
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :type => String.t | nil,
    :status => String.t | nil,
    :source => String.t | nil,
    :opt_in_level => String.t | nil,
    :modified_time => String.t | nil,
    :additional_fields => map() | nil,
    :custom_fields => map() | nil
  }

  def decode(value) do
    value
  end
end

