# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.GiftCard do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :code,
    :name,
    :type,
    :currency_code,
    :amount,
    :initial_amount,
    :status,
    :created_at,
    :avail_to,
    :free_product_ids,
    :message,
    :issuer_email,
    :recipient_email,
    :issuer_name,
    :recipient_name,
    :usage_history,
    :additional_fields,
    :custom_fields
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :code => String.t | nil,
    :name => String.t | nil,
    :type => String.t | nil,
    :currency_code => String.t | nil,
    :amount => float() | nil,
    :initial_amount => float() | nil,
    :status => String.t | nil,
    :created_at => String.t | nil,
    :avail_to => String.t | nil,
    :free_product_ids => String.t | nil,
    :message => String.t | nil,
    :issuer_email => String.t | nil,
    :recipient_email => String.t | nil,
    :issuer_name => String.t | nil,
    :recipient_name => String.t | nil,
    :usage_history => [API2CartOpenAPI.Model.CouponHistory.t] | nil,
    :additional_fields => map() | nil,
    :custom_fields => map() | nil
  }

  alias API2CartOpenAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:usage_history, :list, API2CartOpenAPI.Model.CouponHistory)
  end
end

