# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.Info do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :owner,
    :country,
    :state,
    :state_code,
    :city,
    :street_address,
    :street_address_line_2,
    :zip_code,
    :email,
    :phone,
    :additional_fields,
    :custom_fields
  ]

  @type t :: %__MODULE__{
    :owner => String.t | nil,
    :country => String.t | nil,
    :state => String.t | nil,
    :state_code => String.t | nil,
    :city => String.t | nil,
    :street_address => String.t | nil,
    :street_address_line_2 => String.t | nil,
    :zip_code => String.t | nil,
    :email => String.t | nil,
    :phone => String.t | nil,
    :additional_fields => map() | nil,
    :custom_fields => map() | nil
  }

  def decode(value) do
    value
  end
end

