# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.OrderShipmentAddBatchPayloadInner do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :order_id,
    :store_id,
    :warehouse_id,
    :carrier_id,
    :carrier_name,
    :tracking_number,
    :tracking_link,
    :shipment_provider,
    :items,
    :send_notifications
  ]

  @type t :: %__MODULE__{
    :order_id => String.t,
    :store_id => String.t | nil,
    :warehouse_id => String.t | nil,
    :carrier_id => String.t | nil,
    :carrier_name => String.t | nil,
    :tracking_number => String.t,
    :tracking_link => String.t | nil,
    :shipment_provider => String.t | nil,
    :items => [API2CartOpenAPI.Model.OrderShipmentAddBatchPayloadInnerItemsInner.t] | nil,
    :send_notifications => boolean() | nil
  }

  alias API2CartOpenAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:items, :list, API2CartOpenAPI.Model.OrderShipmentAddBatchPayloadInnerItemsInner)
  end
end

