# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.OrderShipmentAddTrackingNumbersInner do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :carrier_id,
    :tracking_number
  ]

  @type t :: %__MODULE__{
    :carrier_id => String.t | nil,
    :tracking_number => String.t | nil
  }

  def decode(value) do
    value
  end
end

