# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.OrderShipmentAdd do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :order_id,
    :warehouse_id,
    :store_id,
    :shipment_provider,
    :shipping_method,
    :items,
    :tracking_numbers,
    :tracking_link,
    :is_shipped,
    :send_notifications,
    :adjust_stock,
    :check_process_status,
    :tracking_provider,
    :admin_comment,
    :mail_class,
    :ship_date,
    :weight,
    :weight_unit,
    :length,
    :width,
    :height,
    :dimensions_unit,
    :shipping_label_cost,
    :shipping_label_currency,
    :revenue_eligibility,
    :ship_from_country,
    :ship_to_country,
    :incoterm,
    :duty_amount,
    :duty_currency,
    :enable_cache,
    :use_latest_api_version,
    :idempotency_key
  ]

  @type t :: %__MODULE__{
    :order_id => String.t | nil,
    :warehouse_id => String.t | nil,
    :store_id => String.t | nil,
    :shipment_provider => String.t | nil,
    :shipping_method => String.t | nil,
    :items => [API2CartOpenAPI.Model.OrderShipmentAddItemsInner.t] | nil,
    :tracking_numbers => [API2CartOpenAPI.Model.OrderShipmentAddTrackingNumbersInner.t] | nil,
    :tracking_link => String.t | nil,
    :is_shipped => boolean() | nil,
    :send_notifications => boolean() | nil,
    :adjust_stock => boolean() | nil,
    :check_process_status => boolean() | nil,
    :tracking_provider => String.t | nil,
    :admin_comment => String.t | nil,
    :mail_class => String.t | nil,
    :ship_date => String.t | nil,
    :weight => float() | nil,
    :weight_unit => String.t | nil,
    :length => float() | nil,
    :width => float() | nil,
    :height => float() | nil,
    :dimensions_unit => String.t | nil,
    :shipping_label_cost => float() | nil,
    :shipping_label_currency => String.t | nil,
    :revenue_eligibility => boolean() | nil,
    :ship_from_country => String.t | nil,
    :ship_to_country => String.t | nil,
    :incoterm => String.t | nil,
    :duty_amount => float() | nil,
    :duty_currency => String.t | nil,
    :enable_cache => boolean() | nil,
    :use_latest_api_version => boolean() | nil,
    :idempotency_key => String.t | nil
  }

  alias API2CartOpenAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:items, :list, API2CartOpenAPI.Model.OrderShipmentAddItemsInner)
     |> Deserializer.deserialize(:tracking_numbers, :list, API2CartOpenAPI.Model.OrderShipmentAddTrackingNumbersInner)
  end
end

