# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.OrderCalculateShippingRate do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :code,
    :name,
    :price,
    :price_inc_tax,
    :tax,
    :tax_rate,
    :additional_fields,
    :custom_fields
  ]

  @type t :: %__MODULE__{
    :code => String.t | nil,
    :name => String.t | nil,
    :price => float() | nil,
    :price_inc_tax => float() | nil,
    :tax => float() | nil,
    :tax_rate => float() | nil,
    :additional_fields => map() | nil,
    :custom_fields => map() | nil
  }

  def decode(value) do
    value
  end
end

