# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.OrderReturnUpdate do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :return_id,
    :order_id,
    :store_id,
    :item_restock,
    :return_status_id,
    :staff_note,
    :comment,
    :send_notifications,
    :reject_reason,
    :return_action,
    :return_reason,
    :idempotency_key,
    :order_products
  ]

  @type t :: %__MODULE__{
    :return_id => String.t,
    :order_id => String.t | nil,
    :store_id => String.t | nil,
    :item_restock => boolean() | nil,
    :return_status_id => String.t | nil,
    :staff_note => String.t | nil,
    :comment => String.t | nil,
    :send_notifications => boolean() | nil,
    :reject_reason => String.t | nil,
    :return_action => String.t | nil,
    :return_reason => String.t | nil,
    :idempotency_key => String.t | nil,
    :order_products => [API2CartOpenAPI.Model.OrderReturnUpdateOrderProductsInner.t]
  }

  alias API2CartOpenAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:order_products, :list, API2CartOpenAPI.Model.OrderReturnUpdateOrderProductsInner)
  end
end

