# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.OrderShipmentEventAdd do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :shipment_id,
    :order_id,
    :status,
    :store_id,
    :address_1,
    :city,
    :country,
    :state,
    :postcode,
    :message,
    :latitude,
    :longitude,
    :created_at,
    :estimated_delivery_at,
    :idempotency_key
  ]

  @type t :: %__MODULE__{
    :shipment_id => String.t,
    :order_id => String.t | nil,
    :status => String.t,
    :store_id => String.t | nil,
    :address_1 => String.t | nil,
    :city => String.t | nil,
    :country => String.t | nil,
    :state => String.t | nil,
    :postcode => String.t | nil,
    :message => String.t | nil,
    :latitude => float() | nil,
    :longitude => float() | nil,
    :created_at => String.t | nil,
    :estimated_delivery_at => String.t | nil,
    :idempotency_key => String.t | nil
  }

  def decode(value) do
    value
  end
end

