# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.OrderPreestimateShipping do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :method_code,
    :method_name,
    :carrier_code,
    :carrier_name,
    :description,
    :price,
    :price_inc_tax,
    :delivery_time,
    :additional_fields,
    :custom_fields
  ]

  @type t :: %__MODULE__{
    :method_code => String.t | nil,
    :method_name => String.t | nil,
    :carrier_code => String.t | nil,
    :carrier_name => String.t | nil,
    :description => String.t | nil,
    :price => float() | nil,
    :price_inc_tax => float() | nil,
    :delivery_time => String.t | nil,
    :additional_fields => map() | nil,
    :custom_fields => map() | nil
  }

  def decode(value) do
    value
  end
end

