# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.Order do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :order_id,
    :basket_id,
    :channel_id,
    :customer,
    :create_at,
    :currency,
    :shipping_address,
    :billing_address,
    :payment_method,
    :shipping_method,
    :shipping_methods,
    :status,
    :totals,
    :total,
    :discounts,
    :order_products,
    :bundles,
    :modified_at,
    :finished_time,
    :comment,
    :store_id,
    :warehouses_ids,
    :refunds,
    :gift_message,
    :order_details_url,
    :additional_fields,
    :custom_fields
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :order_id => String.t | nil,
    :basket_id => String.t | nil,
    :channel_id => String.t | nil,
    :customer => API2CartOpenAPI.Model.BaseCustomer.t | nil,
    :create_at => API2CartOpenAPI.Model.A2CDateTime.t | nil,
    :currency => API2CartOpenAPI.Model.Currency.t | nil,
    :shipping_address => API2CartOpenAPI.Model.CustomerAddress.t | nil,
    :billing_address => API2CartOpenAPI.Model.CustomerAddress.t | nil,
    :payment_method => API2CartOpenAPI.Model.OrderPaymentMethod.t | nil,
    :shipping_method => API2CartOpenAPI.Model.OrderShippingMethod.t | nil,
    :shipping_methods => [API2CartOpenAPI.Model.OrderShippingMethod.t] | nil,
    :status => API2CartOpenAPI.Model.OrderStatus.t | nil,
    :totals => API2CartOpenAPI.Model.OrderTotals.t | nil,
    :total => API2CartOpenAPI.Model.OrderTotal.t | nil,
    :discounts => [API2CartOpenAPI.Model.OrderTotalsNewDiscount.t] | nil,
    :order_products => [API2CartOpenAPI.Model.OrderItem.t] | nil,
    :bundles => [API2CartOpenAPI.Model.OrderItem.t] | nil,
    :modified_at => API2CartOpenAPI.Model.A2CDateTime.t | nil,
    :finished_time => API2CartOpenAPI.Model.A2CDateTime.t | nil,
    :comment => String.t | nil,
    :store_id => String.t | nil,
    :warehouses_ids => [String.t] | nil,
    :refunds => [API2CartOpenAPI.Model.OrderRefund.t] | nil,
    :gift_message => String.t | nil,
    :order_details_url => String.t | nil,
    :additional_fields => map() | nil,
    :custom_fields => map() | nil
  }

  alias API2CartOpenAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:customer, :struct, API2CartOpenAPI.Model.BaseCustomer)
     |> Deserializer.deserialize(:create_at, :struct, API2CartOpenAPI.Model.A2CDateTime)
     |> Deserializer.deserialize(:currency, :struct, API2CartOpenAPI.Model.Currency)
     |> Deserializer.deserialize(:shipping_address, :struct, API2CartOpenAPI.Model.CustomerAddress)
     |> Deserializer.deserialize(:billing_address, :struct, API2CartOpenAPI.Model.CustomerAddress)
     |> Deserializer.deserialize(:payment_method, :struct, API2CartOpenAPI.Model.OrderPaymentMethod)
     |> Deserializer.deserialize(:shipping_method, :struct, API2CartOpenAPI.Model.OrderShippingMethod)
     |> Deserializer.deserialize(:shipping_methods, :list, API2CartOpenAPI.Model.OrderShippingMethod)
     |> Deserializer.deserialize(:status, :struct, API2CartOpenAPI.Model.OrderStatus)
     |> Deserializer.deserialize(:totals, :struct, API2CartOpenAPI.Model.OrderTotals)
     |> Deserializer.deserialize(:total, :struct, API2CartOpenAPI.Model.OrderTotal)
     |> Deserializer.deserialize(:discounts, :list, API2CartOpenAPI.Model.OrderTotalsNewDiscount)
     |> Deserializer.deserialize(:order_products, :list, API2CartOpenAPI.Model.OrderItem)
     |> Deserializer.deserialize(:bundles, :list, API2CartOpenAPI.Model.OrderItem)
     |> Deserializer.deserialize(:modified_at, :struct, API2CartOpenAPI.Model.A2CDateTime)
     |> Deserializer.deserialize(:finished_time, :struct, API2CartOpenAPI.Model.A2CDateTime)
     |> Deserializer.deserialize(:refunds, :list, API2CartOpenAPI.Model.OrderRefund)
  end
end

