# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.OrderPreestimateShippingListOrderItemInnerOrderItemOptionInner do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :order_item_option_name,
    :order_item_option_id,
    :order_item_option_value,
    :order_item_option_value_id,
    :order_item_option_used_in_combinations
  ]

  @type t :: %__MODULE__{
    :order_item_option_name => String.t | nil,
    :order_item_option_id => String.t | nil,
    :order_item_option_value => String.t | nil,
    :order_item_option_value_id => String.t | nil,
    :order_item_option_used_in_combinations => boolean() | nil
  }

  def decode(value) do
    value
  end
end

