# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.OrderShipmentUpdate do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :shipment_id,
    :order_id,
    :store_id,
    :shipment_provider,
    :tracking_numbers,
    :tracking_link,
    :is_shipped,
    :delivered_at,
    :replace,
    :send_notifications,
    :tracking_provider,
    :items
  ]

  @type t :: %__MODULE__{
    :shipment_id => String.t,
    :order_id => String.t | nil,
    :store_id => String.t | nil,
    :shipment_provider => String.t | nil,
    :tracking_numbers => [API2CartOpenAPI.Model.OrderShipmentAddTrackingNumbersInner.t] | nil,
    :tracking_link => String.t | nil,
    :is_shipped => boolean() | nil,
    :delivered_at => String.t | nil,
    :replace => boolean() | nil,
    :send_notifications => boolean() | nil,
    :tracking_provider => String.t | nil,
    :items => [API2CartOpenAPI.Model.OrderShipmentAddItemsInner.t] | nil
  }

  alias API2CartOpenAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:tracking_numbers, :list, API2CartOpenAPI.Model.OrderShipmentAddTrackingNumbersInner)
     |> Deserializer.deserialize(:items, :list, API2CartOpenAPI.Model.OrderShipmentAddItemsInner)
  end
end

