# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.OrderShipmentAdd do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :order_id,
    :warehouse_id,
    :store_id,
    :shipment_provider,
    :shipping_method,
    :items,
    :tracking_numbers,
    :tracking_link,
    :is_shipped,
    :send_notifications,
    :adjust_stock,
    :enable_cache,
    :check_process_status,
    :use_latest_api_version
  ]

  @type t :: %__MODULE__{
    :order_id => String.t | nil,
    :warehouse_id => String.t | nil,
    :store_id => String.t | nil,
    :shipment_provider => String.t | nil,
    :shipping_method => String.t | nil,
    :items => [API2CartOpenAPI.Model.OrderShipmentAddItemsInner.t] | nil,
    :tracking_numbers => [API2CartOpenAPI.Model.OrderShipmentAddTrackingNumbersInner.t] | nil,
    :tracking_link => String.t | nil,
    :is_shipped => boolean() | nil,
    :send_notifications => boolean() | nil,
    :adjust_stock => boolean() | nil,
    :enable_cache => boolean() | nil,
    :check_process_status => boolean() | nil,
    :use_latest_api_version => boolean() | nil
  }

  alias API2CartOpenAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:items, :list, API2CartOpenAPI.Model.OrderShipmentAddItemsInner)
     |> Deserializer.deserialize(:tracking_numbers, :list, API2CartOpenAPI.Model.OrderShipmentAddTrackingNumbersInner)
  end
end

