# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.OrderStatusRefundItem do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :product_id,
    :variant_id,
    :order_product_id,
    :qty,
    :refund,
    :additional_fields,
    :custom_fields
  ]

  @type t :: %__MODULE__{
    :product_id => String.t | nil,
    :variant_id => String.t | nil,
    :order_product_id => String.t | nil,
    :qty => float() | nil,
    :refund => float() | nil,
    :additional_fields => map() | nil,
    :custom_fields => map() | nil
  }

  def decode(value) do
    value
  end
end

