# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.OrderAbandoned do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :customer,
    :basket_id,
    :basket_url,
    :created_at,
    :modified_at,
    :currency,
    :totals,
    :order_products,
    :additional_fields,
    :custom_fields
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :customer => API2CartOpenAPI.Model.BaseCustomer.t | nil,
    :basket_id => String.t | nil,
    :basket_url => String.t | nil,
    :created_at => API2CartOpenAPI.Model.A2CDateTime.t | nil,
    :modified_at => API2CartOpenAPI.Model.A2CDateTime.t | nil,
    :currency => API2CartOpenAPI.Model.Currency.t | nil,
    :totals => API2CartOpenAPI.Model.OrderTotals.t | nil,
    :order_products => [API2CartOpenAPI.Model.OrderItem.t] | nil,
    :additional_fields => map() | nil,
    :custom_fields => map() | nil
  }

  alias API2CartOpenAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:customer, :struct, API2CartOpenAPI.Model.BaseCustomer)
     |> Deserializer.deserialize(:created_at, :struct, API2CartOpenAPI.Model.A2CDateTime)
     |> Deserializer.deserialize(:modified_at, :struct, API2CartOpenAPI.Model.A2CDateTime)
     |> Deserializer.deserialize(:currency, :struct, API2CartOpenAPI.Model.Currency)
     |> Deserializer.deserialize(:totals, :struct, API2CartOpenAPI.Model.OrderTotals)
     |> Deserializer.deserialize(:order_products, :list, API2CartOpenAPI.Model.OrderItem)
  end
end

