# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.OrderTotals do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :total,
    :subtotal,
    :shipping,
    :tax,
    :discount,
    :additional_fields,
    :custom_fields
  ]

  @type t :: %__MODULE__{
    :total => float() | nil,
    :subtotal => float() | nil,
    :shipping => float() | nil,
    :tax => float() | nil,
    :discount => float() | nil,
    :additional_fields => map() | nil,
    :custom_fields => map() | nil
  }

  def decode(value) do
    value
  end
end

