# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.OrderShipmentAddBatchPayloadInnerItemsInner do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :order_product_id,
    :quantity
  ]

  @type t :: %__MODULE__{
    :order_product_id => String.t,
    :quantity => float()
  }

  def decode(value) do
    value
  end
end

