# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.OrderCalculateTax do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :code,
    :rate,
    :value,
    :additional_fields,
    :custom_fields
  ]

  @type t :: %__MODULE__{
    :code => String.t | nil,
    :rate => float() | nil,
    :value => float() | nil,
    :additional_fields => map() | nil,
    :custom_fields => map() | nil
  }

  def decode(value) do
    value
  end
end

