# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.OrderItem do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :product_id,
    :order_product_id,
    :model,
    :name,
    :price,
    :price_inc_tax,
    :quantity,
    :discount_amount,
    :total_price,
    :tax_percent,
    :tax_value,
    :tax_value_after_discount,
    :options,
    :variant_id,
    :weight_unit,
    :weight,
    :barcode,
    :parent_order_product_id,
    :additional_fields,
    :custom_fields
  ]

  @type t :: %__MODULE__{
    :product_id => String.t | nil,
    :order_product_id => String.t | nil,
    :model => String.t | nil,
    :name => String.t | nil,
    :price => float() | nil,
    :price_inc_tax => float() | nil,
    :quantity => float() | nil,
    :discount_amount => float() | nil,
    :total_price => float() | nil,
    :tax_percent => float() | nil,
    :tax_value => float() | nil,
    :tax_value_after_discount => float() | nil,
    :options => [API2CartOpenAPI.Model.OrderItemOption.t] | nil,
    :variant_id => String.t | nil,
    :weight_unit => String.t | nil,
    :weight => float() | nil,
    :barcode => String.t | nil,
    :parent_order_product_id => String.t | nil,
    :additional_fields => map() | nil,
    :custom_fields => map() | nil
  }

  alias API2CartOpenAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:options, :list, API2CartOpenAPI.Model.OrderItemOption)
  end
end

