# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.OrderReturnUpdateOrderProductsInner do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :order_product_id,
    :order_product_quantity,
    :order_product_status,
    :order_product_action_id
  ]

  @type t :: %__MODULE__{
    :order_product_id => String.t,
    :order_product_quantity => integer(),
    :order_product_status => String.t | nil,
    :order_product_action_id => String.t
  }

  def decode(value) do
    value
  end
end

