# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.OrderCalculateItem do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :product_id,
    :sku,
    :name,
    :quantity,
    :price,
    :price_inc_tax,
    :tax_rate,
    :unit_discount,
    :weight,
    :weight_unit,
    :barcode,
    :variant_id,
    :options,
    :additional_fields,
    :custom_fields
  ]

  @type t :: %__MODULE__{
    :product_id => String.t | nil,
    :sku => String.t | nil,
    :name => String.t | nil,
    :quantity => integer() | nil,
    :price => float() | nil,
    :price_inc_tax => float() | nil,
    :tax_rate => float() | nil,
    :unit_discount => float() | nil,
    :weight => float() | nil,
    :weight_unit => String.t | nil,
    :barcode => String.t | nil,
    :variant_id => String.t | nil,
    :options => [API2CartOpenAPI.Model.OrderItemOption.t] | nil,
    :additional_fields => map() | nil,
    :custom_fields => map() | nil
  }

  alias API2CartOpenAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:options, :list, API2CartOpenAPI.Model.OrderItemOption)
  end
end

