# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.ParamDefinitionFilteringConditionsFilterCondition do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :and,
    :or,
    :not,
    :field,
    :operator,
    :value
  ]

  @type t :: %__MODULE__{
    :and => [map()] | nil,
    :or => [map()] | nil,
    :not => map() | nil,
    :field => String.t | nil,
    :operator => String.t | nil,
    :value => API2CartOpenAPI.Model.ParamDefinitionFilteringConditionsFilterRuleValue.t | nil
  }

  alias API2CartOpenAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:value, :struct, API2CartOpenAPI.Model.ParamDefinitionFilteringConditionsFilterRuleValue)
  end
end

