# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.Product do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :type,
    :u_model,
    :u_sku,
    :name,
    :description,
    :short_description,
    :price,
    :advanced_price,
    :cost_price,
    :unit_price,
    :measure_unit,
    :quantity,
    :inventory,
    :group_items,
    :u_brand_id,
    :u_brand,
    :categories_ids,
    :stores_ids,
    :url,
    :seo_url,
    :meta_title,
    :meta_keywords,
    :meta_description,
    :avail_sale,
    :avail_view,
    :is_virtual,
    :is_downloadable,
    :weight,
    :weight_unit,
    :sort_order,
    :in_stock,
    :backorders,
    :manage_stock,
    :is_stock_managed,
    :on_sale,
    :create_at,
    :modified_at,
    :tax_class_id,
    :special_price,
    :tier_price,
    :group_price,
    :images,
    :product_options,
    :u_upc,
    :u_mpn,
    :u_gtin,
    :u_isbn,
    :u_ean,
    :related_products_ids,
    :up_sell_products_ids,
    :cross_sell_products_ids,
    :dimensions_unit,
    :width,
    :height,
    :length,
    :discounts,
    :additional_fields,
    :custom_fields
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :type => String.t | nil,
    :u_model => String.t | nil,
    :u_sku => String.t | nil,
    :name => String.t | nil,
    :description => String.t | nil,
    :short_description => String.t | nil,
    :price => float() | nil,
    :advanced_price => [API2CartOpenAPI.Model.ProductAdvancedPrice.t] | nil,
    :cost_price => float() | nil,
    :unit_price => float() | nil,
    :measure_unit => String.t | nil,
    :quantity => float() | nil,
    :inventory => [API2CartOpenAPI.Model.ProductInventory.t] | nil,
    :group_items => [API2CartOpenAPI.Model.ProductGroupItem.t] | nil,
    :u_brand_id => String.t | nil,
    :u_brand => String.t | nil,
    :categories_ids => [String.t] | nil,
    :stores_ids => [String.t] | nil,
    :url => String.t | nil,
    :seo_url => String.t | nil,
    :meta_title => String.t | nil,
    :meta_keywords => String.t | nil,
    :meta_description => String.t | nil,
    :avail_sale => boolean() | nil,
    :avail_view => boolean() | nil,
    :is_virtual => boolean() | nil,
    :is_downloadable => boolean() | nil,
    :weight => float() | nil,
    :weight_unit => String.t | nil,
    :sort_order => integer() | nil,
    :in_stock => boolean() | nil,
    :backorders => String.t | nil,
    :manage_stock => String.t | nil,
    :is_stock_managed => boolean() | nil,
    :on_sale => boolean() | nil,
    :create_at => API2CartOpenAPI.Model.A2CDateTime.t | nil,
    :modified_at => API2CartOpenAPI.Model.A2CDateTime.t | nil,
    :tax_class_id => String.t | nil,
    :special_price => API2CartOpenAPI.Model.SpecialPrice.t | nil,
    :tier_price => [API2CartOpenAPI.Model.ProductTierPrice.t] | nil,
    :group_price => [API2CartOpenAPI.Model.ProductGroupPrice.t] | nil,
    :images => [API2CartOpenAPI.Model.Image.t] | nil,
    :product_options => [API2CartOpenAPI.Model.ProductOption.t] | nil,
    :u_upc => String.t | nil,
    :u_mpn => String.t | nil,
    :u_gtin => String.t | nil,
    :u_isbn => String.t | nil,
    :u_ean => String.t | nil,
    :related_products_ids => [String.t] | nil,
    :up_sell_products_ids => [String.t] | nil,
    :cross_sell_products_ids => [String.t] | nil,
    :dimensions_unit => String.t | nil,
    :width => float() | nil,
    :height => float() | nil,
    :length => float() | nil,
    :discounts => [API2CartOpenAPI.Model.Discount.t] | nil,
    :additional_fields => map() | nil,
    :custom_fields => map() | nil
  }

  alias API2CartOpenAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:advanced_price, :list, API2CartOpenAPI.Model.ProductAdvancedPrice)
     |> Deserializer.deserialize(:inventory, :list, API2CartOpenAPI.Model.ProductInventory)
     |> Deserializer.deserialize(:group_items, :list, API2CartOpenAPI.Model.ProductGroupItem)
     |> Deserializer.deserialize(:create_at, :struct, API2CartOpenAPI.Model.A2CDateTime)
     |> Deserializer.deserialize(:modified_at, :struct, API2CartOpenAPI.Model.A2CDateTime)
     |> Deserializer.deserialize(:special_price, :struct, API2CartOpenAPI.Model.SpecialPrice)
     |> Deserializer.deserialize(:tier_price, :list, API2CartOpenAPI.Model.ProductTierPrice)
     |> Deserializer.deserialize(:group_price, :list, API2CartOpenAPI.Model.ProductGroupPrice)
     |> Deserializer.deserialize(:images, :list, API2CartOpenAPI.Model.Image)
     |> Deserializer.deserialize(:product_options, :list, API2CartOpenAPI.Model.ProductOption)
     |> Deserializer.deserialize(:discounts, :list, API2CartOpenAPI.Model.Discount)
  end
end

