# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.ProductOptionAddValuesInner do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :value,
    :display_value,
    :is_default
  ]

  @type t :: %__MODULE__{
    :value => String.t,
    :display_value => String.t | nil,
    :is_default => boolean() | nil
  }

  def decode(value) do
    value
  end
end

