# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.ProductAddGroupPricesInner do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :group_id,
    :price,
    :qty
  ]

  @type t :: %__MODULE__{
    :group_id => String.t | nil,
    :price => float() | nil,
    :qty => integer() | nil
  }

  def decode(value) do
    value
  end
end

