# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.ProductAddSpecificsInner do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :name,
    :value,
    :values,
    :used_for_variations,
    :scale_id,
    :food_details,
    :group_products_details,
    :booking_details
  ]

  @type t :: %__MODULE__{
    :name => String.t | nil,
    :value => String.t | nil,
    :values => [String.t] | nil,
    :used_for_variations => boolean() | nil,
    :scale_id => integer() | nil,
    :food_details => API2CartOpenAPI.Model.ProductAddSpecificsInnerFoodDetails.t | nil,
    :group_products_details => [API2CartOpenAPI.Model.ProductAddSpecificsInnerGroupProductsDetailsInner.t] | nil,
    :booking_details => API2CartOpenAPI.Model.ProductAddSpecificsInnerBookingDetails.t | nil
  }

  alias API2CartOpenAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:food_details, :struct, API2CartOpenAPI.Model.ProductAddSpecificsInnerFoodDetails)
     |> Deserializer.deserialize(:group_products_details, :list, API2CartOpenAPI.Model.ProductAddSpecificsInnerGroupProductsDetailsInner)
     |> Deserializer.deserialize(:booking_details, :struct, API2CartOpenAPI.Model.ProductAddSpecificsInnerBookingDetails)
  end
end

