# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.ProductAddBatchPayloadInnerSalesTax do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :tax_percent,
    :taxable
  ]

  @type t :: %__MODULE__{
    :tax_percent => float() | nil,
    :taxable => boolean() | nil
  }

  def decode(value) do
    value
  end
end

