# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.ProductVariantAddBatchPayloadInner do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :product_id,
    :combination,
    :name,
    :description,
    :short_description,
    :sku,
    :model,
    :price,
    :old_price,
    :cost_price,
    :special_price,
    :sprice_create,
    :sprice_expire,
    :advanced_prices,
    :meta_title,
    :meta_description,
    :meta_keywords,
    :categories_ids,
    :stores_ids,
    :weight,
    :width,
    :height,
    :length,
    :weight_unit,
    :warehouse_id,
    :quantity,
    :manage_stock,
    :in_stock,
    :store_id,
    :lang_id,
    :tax_class_id,
    :backorder_status,
    :status,
    :visible,
    :is_virtual,
    :downloadable,
    :is_default,
    :upc,
    :isbn,
    :mpn,
    :ean,
    :barcode,
    :available_for_sale,
    :is_free_shipping,
    :taxable,
    :seo_url,
    :manufacturer_id,
    :harmonized_system_code,
    :marketplace_item_properties,
    :images,
    :product_images_ids,
    :related_products_ids,
    :up_sell_products_ids,
    :cross_sell_products_ids
  ]

  @type t :: %__MODULE__{
    :product_id => String.t,
    :combination => [API2CartOpenAPI.Model.ProductVariantAddBatchPayloadInnerCombinationInner.t],
    :name => String.t | nil,
    :description => String.t | nil,
    :short_description => String.t | nil,
    :sku => String.t,
    :model => String.t | nil,
    :price => float() | nil,
    :old_price => float() | nil,
    :cost_price => float() | nil,
    :special_price => float() | nil,
    :sprice_create => String.t | nil,
    :sprice_expire => String.t | nil,
    :advanced_prices => [API2CartOpenAPI.Model.ProductUpdateBatchPayloadInnerAdvancedPricesInner.t] | nil,
    :meta_title => float() | nil,
    :meta_description => float() | nil,
    :meta_keywords => [String.t] | nil,
    :categories_ids => [String.t] | nil,
    :stores_ids => [String.t] | nil,
    :weight => float() | nil,
    :width => float() | nil,
    :height => float() | nil,
    :length => float() | nil,
    :weight_unit => String.t | nil,
    :warehouse_id => String.t | nil,
    :quantity => float() | nil,
    :manage_stock => boolean() | nil,
    :in_stock => boolean() | nil,
    :store_id => String.t | nil,
    :lang_id => String.t | nil,
    :tax_class_id => String.t | nil,
    :backorder_status => String.t | nil,
    :status => String.t | nil,
    :visible => String.t | nil,
    :is_virtual => boolean() | nil,
    :downloadable => boolean() | nil,
    :is_default => boolean() | nil,
    :upc => String.t | nil,
    :isbn => String.t | nil,
    :mpn => String.t | nil,
    :ean => String.t | nil,
    :barcode => String.t | nil,
    :available_for_sale => boolean() | nil,
    :is_free_shipping => boolean() | nil,
    :taxable => boolean() | nil,
    :seo_url => String.t | nil,
    :manufacturer_id => String.t | nil,
    :harmonized_system_code => String.t | nil,
    :marketplace_item_properties => map() | nil,
    :images => [API2CartOpenAPI.Model.ProductAddBatchPayloadInnerImagesInner.t] | nil,
    :product_images_ids => [String.t] | nil,
    :related_products_ids => [String.t] | nil,
    :up_sell_products_ids => [String.t] | nil,
    :cross_sell_products_ids => [String.t] | nil
  }

  alias API2CartOpenAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:combination, :list, API2CartOpenAPI.Model.ProductVariantAddBatchPayloadInnerCombinationInner)
     |> Deserializer.deserialize(:advanced_prices, :list, API2CartOpenAPI.Model.ProductUpdateBatchPayloadInnerAdvancedPricesInner)
     |> Deserializer.deserialize(:images, :list, API2CartOpenAPI.Model.ProductAddBatchPayloadInnerImagesInner)
  end
end

