# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.ProductAddSalesTax do
  @moduledoc """
  Percent of an item's price to be charged as the sales tax for the order. Look at cart.info method response for allowed values.<hr><div style=\"font-style:normal\">Param structure:<div style=\"margin-left: 2%;\"><code style=\"padding:0; background-color:#ffffff;font-size:85%;font-family:monospace;\">sales_tax[<b>tax_percent</b>] = decimal (##.###)</br>sales_tax[<b>tax_state</b>] = string</br>sales_tax[<b>shipping_inc_in_tax</b>] = bool</br></code></div></div>
  """

  @derive Jason.Encoder
  defstruct [
    :tax_percent,
    :tax_state,
    :shipping_inc_in_tax
  ]

  @type t :: %__MODULE__{
    :tax_percent => float() | nil,
    :tax_state => String.t | nil,
    :shipping_inc_in_tax => boolean() | nil
  }

  def decode(value) do
    value
  end
end

