# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.ProductVariantAddBatchPayloadInnerCombinationInner do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :option_name,
    :option_value_name
  ]

  @type t :: %__MODULE__{
    :option_name => String.t,
    :option_value_name => String.t
  }

  def decode(value) do
    value
  end
end

