# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.ProductPriceUpdate do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :product_id,
    :group_prices
  ]

  @type t :: %__MODULE__{
    :product_id => String.t | nil,
    :group_prices => [API2CartOpenAPI.Model.ProductPriceUpdateGroupPricesInner.t] | nil
  }

  alias API2CartOpenAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:group_prices, :list, API2CartOpenAPI.Model.ProductPriceUpdateGroupPricesInner)
  end
end

