# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.ProductOptionAdd do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :name,
    :type,
    :product_id,
    :default_option_value,
    :option_values,
    :description,
    :avail,
    :sort_order,
    :required,
    :values,
    :clear_cache
  ]

  @type t :: %__MODULE__{
    :name => String.t,
    :type => String.t,
    :product_id => String.t | nil,
    :default_option_value => String.t | nil,
    :option_values => String.t | nil,
    :description => String.t | nil,
    :avail => boolean() | nil,
    :sort_order => integer() | nil,
    :required => boolean() | nil,
    :values => [API2CartOpenAPI.Model.ProductOptionAddValuesInner.t] | nil,
    :clear_cache => boolean() | nil
  }

  alias API2CartOpenAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:values, :list, API2CartOpenAPI.Model.ProductOptionAddValuesInner)
  end
end

