# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.ProductReview do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :product_id,
    :customer_id,
    :nick_name,
    :email,
    :summary,
    :message,
    :rating,
    :ratings,
    :status,
    :created_time,
    :modified_time,
    :medias,
    :additional_fields,
    :custom_fields
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :product_id => String.t | nil,
    :customer_id => String.t | nil,
    :nick_name => String.t | nil,
    :email => String.t | nil,
    :summary => String.t | nil,
    :message => String.t | nil,
    :rating => float() | nil,
    :ratings => [API2CartOpenAPI.Model.ProductReviewRating.t] | nil,
    :status => String.t | nil,
    :created_time => API2CartOpenAPI.Model.A2CDateTime.t | nil,
    :modified_time => API2CartOpenAPI.Model.A2CDateTime.t | nil,
    :medias => [API2CartOpenAPI.Model.Media.t] | nil,
    :additional_fields => map() | nil,
    :custom_fields => map() | nil
  }

  alias API2CartOpenAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:ratings, :list, API2CartOpenAPI.Model.ProductReviewRating)
     |> Deserializer.deserialize(:created_time, :struct, API2CartOpenAPI.Model.A2CDateTime)
     |> Deserializer.deserialize(:modified_time, :struct, API2CartOpenAPI.Model.A2CDateTime)
     |> Deserializer.deserialize(:medias, :list, API2CartOpenAPI.Model.Media)
  end
end

