# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.ProductVariantImageAdd do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :product_id,
    :product_variant_id,
    :store_id,
    :image_name,
    :type,
    :url,
    :content,
    :label,
    :mime,
    :position,
    :option_id,
    :idempotency_key
  ]

  @type t :: %__MODULE__{
    :product_id => String.t | nil,
    :product_variant_id => String.t,
    :store_id => String.t | nil,
    :image_name => String.t,
    :type => String.t,
    :url => String.t | nil,
    :content => String.t | nil,
    :label => String.t | nil,
    :mime => String.t | nil,
    :position => integer() | nil,
    :option_id => String.t | nil,
    :idempotency_key => String.t | nil
  }

  def decode(value) do
    value
  end
end

