# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.ProductVariantAddBatch do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :clear_cache,
    :reindex,
    :payload,
    :idempotency_key
  ]

  @type t :: %__MODULE__{
    :clear_cache => boolean() | nil,
    :reindex => boolean() | nil,
    :payload => [API2CartOpenAPI.Model.ProductVariantAddBatchPayloadInner.t],
    :idempotency_key => String.t | nil
  }

  alias API2CartOpenAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:payload, :list, API2CartOpenAPI.Model.ProductVariantAddBatchPayloadInner)
  end
end

