# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.ProductTaxAdd do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :product_id,
    :name,
    :tax_rates
  ]

  @type t :: %__MODULE__{
    :product_id => String.t | nil,
    :name => String.t,
    :tax_rates => [API2CartOpenAPI.Model.ProductTaxAddTaxRatesInner.t]
  }

  alias API2CartOpenAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:tax_rates, :list, API2CartOpenAPI.Model.ProductTaxAddTaxRatesInner)
  end
end

