# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.ProductAdvancedPrice do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :value,
    :avail,
    :group_id,
    :quantity_from,
    :start_time,
    :expire_time,
    :additional_fields,
    :custom_fields
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :value => float() | nil,
    :avail => boolean() | nil,
    :group_id => String.t | nil,
    :quantity_from => float() | nil,
    :start_time => API2CartOpenAPI.Model.A2CDateTime.t | nil,
    :expire_time => API2CartOpenAPI.Model.A2CDateTime.t | nil,
    :additional_fields => map() | nil,
    :custom_fields => map() | nil
  }

  alias API2CartOpenAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:start_time, :struct, API2CartOpenAPI.Model.A2CDateTime)
     |> Deserializer.deserialize(:expire_time, :struct, API2CartOpenAPI.Model.A2CDateTime)
  end
end

