# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.ProductAddPersonalizationDetails do
  @moduledoc """
  Defines personalization settings for the listing. To enable personalization, is_personalizable must be set to true. When enabled, additional fields may be used to configure the personalization experience, including whether it is required (personalization_is_required), the maximum character limit (personalization_char_count_max), and buyer instructions (personalization_instructions). All related fields are only applicable if personalization is enabled.
  """

  @derive Jason.Encoder
  defstruct [
    :is_personalizable,
    :personalization_is_required,
    :personalization_char_count_max,
    :personalization_instructions
  ]

  @type t :: %__MODULE__{
    :is_personalizable => boolean(),
    :personalization_is_required => boolean() | nil,
    :personalization_char_count_max => integer() | nil,
    :personalization_instructions => String.t | nil
  }

  def decode(value) do
    value
  end
end

