# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.ProductAddSpecificsInnerGroupProductsDetailsInner do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :quantity
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :quantity => integer()
  }

  def decode(value) do
    value
  end
end

