# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.ProductAddSpecificsInnerBookingDetails do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :location,
    :type,
    :session_duration,
    :session_gap,
    :sessions_count,
    :time_strict_value,
    :time_strict_type,
    :availabilities,
    :overrides
  ]

  @type t :: %__MODULE__{
    :location => String.t,
    :type => String.t,
    :session_duration => integer() | nil,
    :session_gap => integer() | nil,
    :sessions_count => integer(),
    :time_strict_value => float(),
    :time_strict_type => String.t,
    :availabilities => [API2CartOpenAPI.Model.ProductAddSpecificsInnerBookingDetailsAvailabilitiesInner.t],
    :overrides => [API2CartOpenAPI.Model.ProductAddSpecificsInnerBookingDetailsOverridesInner.t] | nil
  }

  alias API2CartOpenAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:availabilities, :list, API2CartOpenAPI.Model.ProductAddSpecificsInnerBookingDetailsAvailabilitiesInner)
     |> Deserializer.deserialize(:overrides, :list, API2CartOpenAPI.Model.ProductAddSpecificsInnerBookingDetailsOverridesInner)
  end
end

