# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.ProductAddBatchPayloadInnerAdvancedPricesInner do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :value,
    :group_id,
    :quantity,
    :start_time,
    :expire_time
  ]

  @type t :: %__MODULE__{
    :value => float(),
    :group_id => integer() | nil,
    :quantity => float(),
    :start_time => String.t | nil,
    :expire_time => String.t | nil
  }

  def decode(value) do
    value
  end
end

