# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.ShipmentEvent do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :status,
    :created_at,
    :estimated_delivery_at,
    :message,
    :address,
    :additional_fields,
    :custom_fields
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :status => String.t | nil,
    :created_at => API2CartOpenAPI.Model.A2CDateTime.t | nil,
    :estimated_delivery_at => API2CartOpenAPI.Model.A2CDateTime.t | nil,
    :message => String.t | nil,
    :address => API2CartOpenAPI.Model.CustomerAddress.t | nil,
    :additional_fields => map() | nil,
    :custom_fields => map() | nil
  }

  alias API2CartOpenAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:created_at, :struct, API2CartOpenAPI.Model.A2CDateTime)
     |> Deserializer.deserialize(:estimated_delivery_at, :struct, API2CartOpenAPI.Model.A2CDateTime)
     |> Deserializer.deserialize(:address, :struct, API2CartOpenAPI.Model.CustomerAddress)
  end
end

