# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.StoreAttribute do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :code,
    :type,
    :name,
    :default_values,
    :position,
    :visible,
    :required,
    :system,
    :values,
    :store_id,
    :lang_id,
    :additional_fields,
    :custom_fields
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :code => String.t | nil,
    :type => String.t | nil,
    :name => String.t | nil,
    :default_values => [String.t] | nil,
    :position => integer() | nil,
    :visible => boolean() | nil,
    :required => boolean() | nil,
    :system => boolean() | nil,
    :values => [String.t] | nil,
    :store_id => String.t | nil,
    :lang_id => String.t | nil,
    :additional_fields => map() | nil,
    :custom_fields => map() | nil
  }

  def decode(value) do
    value
  end
end

