# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.TaxClassCountries do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :name,
    :code,
    :tax,
    :tax_type,
    :states,
    :additional_fields,
    :custom_fields
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :name => String.t | nil,
    :code => String.t | nil,
    :tax => float() | nil,
    :tax_type => integer() | nil,
    :states => [API2CartOpenAPI.Model.TaxClassStates.t] | nil,
    :additional_fields => map() | nil,
    :custom_fields => map() | nil
  }

  alias API2CartOpenAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:states, :list, API2CartOpenAPI.Model.TaxClassStates)
  end
end

