# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.TaxClassStates do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :tax,
    :tax_type,
    :name,
    :code,
    :zip_codes,
    :additional_fields,
    :custom_fields
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :tax => float() | nil,
    :tax_type => integer() | nil,
    :name => String.t | nil,
    :code => String.t | nil,
    :zip_codes => [API2CartOpenAPI.Model.TaxClassZipCodes.t] | nil,
    :additional_fields => map() | nil,
    :custom_fields => map() | nil
  }

  alias API2CartOpenAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:zip_codes, :list, API2CartOpenAPI.Model.TaxClassZipCodes)
  end
end

