# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.TaxClassZipCodes do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :is_range,
    :range,
    :fields,
    :additional_fields,
    :custom_fields
  ]

  @type t :: %__MODULE__{
    :is_range => boolean() | nil,
    :range => [String.t] | nil,
    :fields => [API2CartOpenAPI.Model.TaxClassZipCodesRange.t] | nil,
    :additional_fields => map() | nil,
    :custom_fields => map() | nil
  }

  alias API2CartOpenAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:fields, :list, API2CartOpenAPI.Model.TaxClassZipCodesRange)
  end
end

