# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.WebhookEvent do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :webhook_name,
    :entity,
    :action,
    :filterable_fields,
    :additional_fields,
    :custom_fields
  ]

  @type t :: %__MODULE__{
    :webhook_name => String.t | nil,
    :entity => String.t | nil,
    :action => String.t | nil,
    :filterable_fields => map() | nil,
    :additional_fields => map() | nil,
    :custom_fields => map() | nil
  }

  def decode(value) do
    value
  end
end

