# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule API2CartOpenAPI.Model.Webhook do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :label,
    :store_id,
    :lang_id,
    :active,
    :callback,
    :fields,
    :created_at,
    :updated_at,
    :entity,
    :action,
    :additional_fields,
    :custom_fields
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :label => String.t | nil,
    :store_id => String.t | nil,
    :lang_id => String.t | nil,
    :active => boolean() | nil,
    :callback => String.t | nil,
    :fields => String.t | nil,
    :created_at => String.t | nil,
    :updated_at => String.t | nil,
    :entity => String.t | nil,
    :action => String.t | nil,
    :additional_fields => map() | nil,
    :custom_fields => map() | nil
  }

  def decode(value) do
    value
  end
end

